### PR TITLE
Ensure that PHPCS report is present before extracing any info

### LINKED ISSUE #226: PHP CodeSniffer checks pass when phpcs fails
It appears that `phpcs` won't create the `phpcs-report` if it fails with a fatal error. This causes `PHP_CodeSniffer` to pass.

```
## PHP_CodeSniffer
PHP Fatal error:  Uncaught PHP_CodeSniffer_Exception: Referenced sniff "WordPress.PHP.DisallowAlternativePHPTags.MaybeASPShortOpenTagFound" does not exist in phar:///private/tmp/dev-lib-bin/phpcs/CodeSniffer.php:1167
Stack trace:
#0 phar:///private/tmp/dev-lib-bin/phpcs/CodeSniffer.php(780): PHP_CodeSniffer->_expandRulesetReference(Object(SimpleXMLElement), '/Users/kaspars/...', 0)
#1 phar:///private/tmp/dev-lib-bin/phpcs/CodeSniffer.php(578): PHP_CodeSniffer->processRuleset('/Users/kaspars/...')
#2 phar:///private/tmp/dev-lib-bin/phpcs/CodeSniffer/CLI.php(956): PHP_CodeSniffer->initStandard(Array, Array, Array)
#3 phar:///private/tmp/dev-lib-bin/phpcs/CodeSniffer/CLI.php(113): PHP_CodeSniffer_CLI->process()
#4 /private/tmp/dev-lib-bin/phpcs(6): PHP_CodeSniffer_CLI->runphpcs()
#5 {main}
  thrown in phar:///private/tmp/dev-lib-bin/phpcs/CodeSniffer.php on line 1167

Fatal error: Uncaught PHP_CodeSniffer_Exception: Referenced sniff "WordPress.PHP.DisallowAlternativePHPTags.MaybeASPShortOpenTagFound" does not exist in phar:///private/tmp/dev-lib-bin/phpcs/CodeSniffer.php:1167
Stack trace:
#0 phar:///private/tmp/dev-lib-bin/phpcs/CodeSniffer.php(780): PHP_CodeSniffer->_expandRulesetReference(Object(SimpleXMLElement), '/Users/kaspars/...', 0)
#1 phar:///private/tmp/dev-lib-bin/phpcs/CodeSniffer.php(578): PHP_CodeSniffer->processRuleset('/Users/kaspars/...')
#2 phar:///private/tmp/dev-lib-bin/phpcs/CodeSniffer/CLI.php(956): PHP_CodeSniffer->initStandard(Array, Array, Array)
#3 phar:///private/tmp/dev-lib-bin/phpcs/CodeSniffer/CLI.php(113): PHP_CodeSniffer_CLI->process()
#4 /private/tmp/dev-lib-bin/phpcs(6): PHP_CodeSniffer_CLI->runphpcs()
#5 {main}
  thrown in phar:///private/tmp/dev-lib-bin/phpcs/CodeSniffer.php on line 1167
cat: /var/folders/94/vv5vyms51914rpphzb306bzw0000gn/T/tmp.hL0F6dWq/phpcs-report: No such file or directory
Skipping PHPUnit as requested via DEV_LIB_SKIP / DEV_LIB_ONLY
```

### PR DESCRIPTION
**Pull request by kasparsd**
Fixes #226.

Assume that missing PHPCS report file is because of failed PHPCS checks.

### CODE REVIEW

File: check-diff.sh [hunk 1]
```diff
@@ -844,7 +844,9 @@ function lint_php_files {
 			echo "## PHP_CodeSniffer"
 			cd "$LINTING_DIRECTORY"
 			if ! cat "$TEMP_DIRECTORY/paths-scope-php" | remove_diff_range | xargs phpcs -s --report-emacs="$TEMP_DIRECTORY/phpcs-report" --standard="$( if [ ! -z "$PHPCS_RULESET_FILE" ]; then echo "$PHPCS_RULESET_FILE"; else echo "$WPCS_STANDARD"; fi )" $( if [ -n "$PHPCS_IGNORE" ]; then echo --ignore="$PHPCS_IGNORE"; fi ); then
-				if [ "$CHECK_SCOPE" == 'patches' ]; then
+				if [ ! -s "$TEMP_DIRECTORY/phpcs-report" ]; then
```
Comment (westonruter) [inline check-diff.sh]: This should work. But also what about looking at`$?`? I assume that it would be the exit code of `phpcs`, I'm guessing `254`. If it outputs a specific exit code when a fatal error happens, then that could be checked for here instead:

```bash
php_exit_code=$?
if [ "$php_exit_code" -gt 200 ];then
    return $php_exit_code
fi
```

Comment (kasparsd) [inline check-diff.sh]: @westonruter `$?` is actually `0` right after the `phpcs` check.
